// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleFEM.Data;

#nullable disable

namespace SimpleFEM.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251218090918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SimpleFEM.Core.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("INodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JNodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("INodeId");

                    b.HasIndex("JNodeId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("SimpleFEM.Core.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("SimpleFEM.Core.Models.Line", b =>
                {
                    b.HasOne("SimpleFEM.Core.Models.Node", "INode")
                        .WithMany()
                        .HasForeignKey("INodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleFEM.Core.Models.Node", "JNode")
                        .WithMany()
                        .HasForeignKey("JNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("INode");

                    b.Navigation("JNode");
                });
#pragma warning restore 612, 618
        }
    }
}
